import fs from "node:fs";
import { mkdir, mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, describe, expect, it, vi } from "vitest";
import {
	generateThemeBuildFiles,
	nazareThemePlugin,
	scanTheme,
} from "../theme/default/nazare/vite-plugin.js";

const manifestPath = new URL("../nazare.registry.yml", import.meta.url);
const tempRoots = [];

async function makeTheme() {
	const root = await mkdtemp(join(tmpdir(), "nazare-plugin-test-"));
	tempRoots.push(root);
	await mkdir(join(root, "sections"), { recursive: true });
	await mkdir(join(root, "snippets"), { recursive: true });
	await mkdir(join(root, "scripts", "sections"), { recursive: true });
	await mkdir(join(root, "scripts", "snippets"), { recursive: true });
	await mkdir(join(root, "scripts", "behaviors"), { recursive: true });
	return root;
}

async function readText(root, relativePath) {
	return readFile(join(root, relativePath), "utf8");
}

async function writeText(root, relativePath, content) {
	await mkdir(join(root, relativePath, ".."), { recursive: true });
	await writeFile(join(root, relativePath), content);
}

afterEach(async () => {
	await Promise.all(
		tempRoots
			.splice(0)
			.map((root) => rm(root, { recursive: true, force: true })),
	);
});

describe("theme build plugin", () => {
	it("declares vendored plugin file in the registry manifest", async () => {
		const manifest = await readFile(manifestPath, "utf8");

		expect(manifest).toContain(
			"- from: theme/default/nazare/vite-plugin.js\n      to: nazare/vite-plugin.js",
		);
	});

	it("scans sections, snippets, behavior module keys, and css directives", async () => {
		const root = await makeTheme();
		await writeText(
			root,
			"sections/s-hero.liquid",
			`{% comment %} nazare:css preload {% endcomment %}
<section data-nazare-use="sections/s-hero">
  {% render 'c-button' %}
</section>`,
		);
		await writeText(
			root,
			"snippets/c-button.liquid",
			`<button data-nazare-use="behaviors/scroll-snap">Button</button>`,
		);
		await writeText(
			root,
			"scripts/sections/s-hero.js",
			"export function init() {}\n",
		);
		await writeText(
			root,
			"scripts/behaviors/scroll-snap.js",
			"export function init() {}\n",
		);

		const graph = scanTheme(root);

		expect(graph.sections).toEqual([
			{
				name: "s-hero",
				cssMode: "preload",
				sources: ["sections/s-hero.liquid", "snippets/c-button.liquid"],
			},
		]);
		expect(graph.moduleKeys).toEqual([
			"behaviors/scroll-snap",
			"sections/s-hero",
		]);
	});

	it("generates marked CSS entries, bridge snippets, and runtime", async () => {
		const root = await makeTheme();
		await writeText(
			root,
			"sections/s-main.liquid",
			"{% render 'section-css', section_name: 's-main' %}\n<section>Main</section>\n",
		);

		generateThemeBuildFiles(root);

		await expect(readText(root, "styles/s-main.css")).resolves.toContain(
			"Generated by Nazare. Do not edit directly.",
		);
		await expect(readText(root, "styles/s-main.css")).resolves.toContain(
			'@source "../sections/s-main.liquid";',
		);
		await expect(
			readText(root, "snippets/section-css.liquid"),
		).resolves.toContain("{% when 's-main' %}");
		await expect(
			readText(root, "snippets/section-css-preloads.liquid"),
		).resolves.toContain("Generated by Nazare. Do not edit directly.");
		await expect(readText(root, "scripts/theme.js")).resolves.toContain(
			'import.meta.glob("./behaviors/*.js")',
		);
		await expect(readText(root, "scripts/theme.js")).resolves.toContain(
			'document.addEventListener("shopify:section:load"',
		);
	});

	it("rejects multiple module keys on one data-nazare-use attribute", async () => {
		const root = await makeTheme();
		await writeText(
			root,
			"sections/s-main.liquid",
			'<section data-nazare-use="behaviors/a behaviors/b"></section>',
		);

		expect(() => scanTheme(root)).toThrow("exactly one module key");
	});

	it("rejects missing snippets and missing JS modules", async () => {
		const missingSnippetRoot = await makeTheme();
		await writeText(
			missingSnippetRoot,
			"sections/s-main.liquid",
			"<section>{% render 'c-missing' %}</section>",
		);

		expect(() => scanTheme(missingSnippetRoot)).toThrow("Missing snippet");

		const missingJsRoot = await makeTheme();
		await writeText(
			missingJsRoot,
			"sections/s-main.liquid",
			'<section data-nazare-use="behaviors/missing"></section>',
		);

		expect(() => scanTheme(missingJsRoot)).toThrow("Missing JS module");
	});

	it("rejects invalid css directives", async () => {
		const root = await makeTheme();
		await writeText(
			root,
			"sections/s-main.liquid",
			"<section>Main</section>\n{% comment %} nazare:css preload {% endcomment %}",
		);

		expect(() => scanTheme(root)).toThrow("before rendered output");
	});

	it("does not rewrite unchanged generated files", async () => {
		const root = await makeTheme();
		await writeText(
			root,
			"sections/s-main.liquid",
			"{% render 'section-css', section_name: 's-main' %}\n<section>Main</section>\n",
		);

		generateThemeBuildFiles(root);
		const writeFileSync = vi.spyOn(fs, "writeFileSync");

		generateThemeBuildFiles(root);

		expect(writeFileSync).not.toHaveBeenCalled();
		writeFileSync.mockRestore();
	});

	it("cleans stale generated section CSS only when marked", async () => {
		const root = await makeTheme();
		await mkdir(join(root, "styles"), { recursive: true });
		await writeText(
			root,
			"styles/s-old.css",
			"/* Generated by Nazare. Do not edit directly. */\n",
		);
		await writeText(root, "styles/user.css", "/* user */\n");
		await writeText(
			root,
			"sections/s-main.liquid",
			"<section>Main</section>\n",
		);

		generateThemeBuildFiles(root);

		await expect(readText(root, "styles/s-main.css")).resolves.toContain(
			"Generated by Nazare",
		);
		await expect(readText(root, "styles/user.css")).resolves.toBe(
			"/* user */\n",
		);
		await expect(readText(root, "styles/s-old.css")).rejects.toMatchObject({
			code: "ENOENT",
		});
	});

	it("vite plugin returns generated inputs and reports dynamic render warnings", async () => {
		const root = await makeTheme();
		await writeText(
			root,
			"sections/s-main.liquid",
			"<section>{% render snippet_name %}</section>\n",
		);
		const plugin = nazareThemePlugin();
		const config = plugin.config({ root });
		const warn = vi.fn();

		plugin.buildStart.call({ warn });

		expect(config.build.rollupOptions.input).toMatchObject({
			theme: "scripts/theme.js",
			"s-main": "styles/s-main.css",
		});
		expect(warn).toHaveBeenCalledWith(
			"Dynamic render not followed in sections/s-main.liquid",
		);
	});
});
