import { execFile } from "node:child_process";
import { mkdir, mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { promisify } from "node:util";
import { afterEach, describe, expect, it } from "vitest";

const execFileAsync = promisify(execFile);
const cliPath = new URL("../bin/nazare.js", import.meta.url);
const tempRoots = [];

async function makeTempDir(prefix = "nazare-theme-pull-test-") {
	const root = await mkdtemp(join(tmpdir(), prefix));
	tempRoots.push(root);
	return root;
}

async function runCli(args, options = {}) {
	try {
		const { stdout, stderr } = await execFileAsync(
			process.execPath,
			[cliPath.pathname, ...args],
			{
				cwd: options.cwd,
				encoding: "utf8",
				env: { ...process.env, ...options.env },
			},
		);
		return { code: 0, stdout, stderr };
	} catch (error) {
		return {
			code: error.code,
			stdout: error.stdout ?? "",
			stderr: error.stderr ?? "",
		};
	}
}

async function writeRegistry(root, manifest) {
	await writeFile(join(root, "nazare.registry.yml"), manifest);
}

afterEach(async () => {
	await Promise.all(
		tempRoots
			.splice(0)
			.map((root) => rm(root, { recursive: true, force: true })),
	);
});

describe("nazare theme pull", () => {
	it("copies manifest-declared theme files and updates lockfile", async () => {
		const cwd = await makeTempDir();
		await runCli(["init"], { cwd });

		const result = await runCli(["theme", "pull", "--yes"], { cwd });

		expect(result).toMatchObject({ code: 0, stderr: "" });
		expect(result.stdout).toContain("Wrote layout/theme.liquid");
		expect(
			await readFile(join(cwd, "layout", "theme.liquid"), "utf8"),
		).toContain("{{ content_for_layout }}");
		expect(
			await readFile(join(cwd, "nazare", "vite-plugin.js"), "utf8"),
		).toContain("Generated by Nazare");
		expect(await readFile(join(cwd, "package.json"), "utf8")).toContain(
			'"build": "vite build"',
		);
		const lockfile = await readFile(join(cwd, "nazare.lock.yml"), "utf8");
		expect(lockfile).toContain(
			"theme:\n  version: 1.0.0\n  source: theme/default",
		);
		expect(lockfile).toContain("path: layout/theme.liquid");
	});

	it("fails before writes when not initialized", async () => {
		const cwd = await makeTempDir();
		const result = await runCli(["theme", "pull", "--yes"], { cwd });

		expect(result.code).not.toBe(0);
		expect(result.stderr).toContain("nazare.config.yml");
	});

	it("does not overwrite conflicts without --yes", async () => {
		const cwd = await makeTempDir();
		await runCli(["init"], { cwd });
		await mkdir(join(cwd, "layout"));
		await writeFile(join(cwd, "layout", "theme.liquid"), "existing layout\n");

		const result = await runCli(["theme", "pull"], { cwd });

		expect(result.code).not.toBe(0);
		expect(result.stderr).toContain("Theme file conflicts require --yes");
		expect(await readFile(join(cwd, "layout", "theme.liquid"), "utf8")).toBe(
			"existing layout\n",
		);
	});

	it("overwrites conflicts with --yes", async () => {
		const cwd = await makeTempDir();
		await runCli(["init"], { cwd });
		await mkdir(join(cwd, "layout"));
		await writeFile(join(cwd, "layout", "theme.liquid"), "existing layout\n");

		const result = await runCli(["theme", "pull", "--yes"], { cwd });

		expect(result).toMatchObject({ code: 0, stderr: "" });
		expect(
			await readFile(join(cwd, "layout", "theme.liquid"), "utf8"),
		).toContain("{{ content_for_layout }}");
	});

	it("fails before writes for unsafe manifest paths", async () => {
		const cwd = await makeTempDir();
		const registry = await makeTempDir("nazare-registry-test-");
		await writeRegistry(
			registry,
			`schemaVersion: 1

registry:
  name: nazare

theme:
  version: 1.0.0
  source: theme/default
  files:
    - from: ../secret.txt
      to: layout/theme.liquid

components: {}
`,
		);
		await writeFile(
			join(cwd, "nazare.config.yml"),
			`schemaVersion: 1

registry:
  name: nazare
  repo: github.com/fedorivanenko/nazare
  ref: refs/heads/main
  manifest: nazare.registry.yml
`,
		);
		await writeFile(
			join(cwd, "nazare.lock.yml"),
			`schemaVersion: 1

registry:
  name: nazare
  repo: github.com/fedorivanenko/nazare
  ref: refs/heads/main
  manifest: nazare.registry.yml

components: {}
`,
		);

		const result = await runCli(["theme", "pull", "--yes"], {
			cwd,
			env: { NAZARE_REGISTRY_DIR: registry },
		});

		expect(result.code).not.toBe(0);
		expect(result.stderr).toContain("Unsafe theme file source path");
	});

	it("pulls scaffold that can install dependencies and build", async () => {
		const cwd = await makeTempDir();
		await runCli(["init"], { cwd });
		await runCli(["theme", "pull", "--yes"], { cwd });

		const install = await execFileAsync("npm", ["install", "--silent"], {
			cwd,
			encoding: "utf8",
		});
		expect(install.stderr).toBe("");
		const build = await execFileAsync("npm", ["run", "build"], {
			cwd,
			encoding: "utf8",
		});

		expect(build.stdout).toContain("vite build");
		expect(await readFile(join(cwd, "assets", "base.css"), "utf8")).toContain(
			"@layer",
		);
		expect(await readFile(join(cwd, "scripts", "theme.js"), "utf8")).toContain(
			"Generated by Nazare",
		);
		expect(await readFile(join(cwd, "assets", "theme.js"), "utf8")).toContain(
			"[nazare]",
		);
	}, 60_000);
});
