// Generated by Nazare. Do not edit directly. This file is generated and may be overwritten.

const modules = {
  ...import.meta.glob("./sections/*.js"),
  ...import.meta.glob("./snippets/*.js"),
  ...import.meta.glob("./behaviors/*.js"),
};

const modulePromises = new Map();
const mounted = new WeakMap();

async function importModule(key) {
  const load = modules[`./${key}.js`];

  if (!load) {
    console.warn(`[nazare] Missing JS module for ${key}`);
    return null;
  }

  try {
    return await load();
  } catch (error) {
    console.warn(`[nazare] Failed to import JS module for ${key}`, error);
    return null;
  }
}

function nazareNodes(root) {
  const selector = "[data-nazare-use]";
  const nodes = [...root.querySelectorAll(selector)];

  if (root.matches?.(selector)) {
    nodes.unshift(root);
  }

  return nodes;
}

export async function initNazare(root = document) {
  for (const node of nazareNodes(root)) {
    const key = node.dataset.nazareUse;

    if (mounted.get(node)?.key === key) continue;

    if (!modulePromises.has(key)) {
      modulePromises.set(key, importModule(key));
    }

    const module = await modulePromises.get(key);
    if (!module?.init) continue;

    try {
      module.init(node);
      mounted.set(node, { key, module });
    } catch (error) {
      console.warn(`[nazare] Failed to initialize JS module for ${key}`, error);
    }
  }
}

export function destroyNazare(root = document) {
  for (const node of nazareNodes(root)) {
    const mount = mounted.get(node);
    if (!mount) continue;

    try {
      mount.module.destroy?.(node);
    } catch (error) {
      console.warn(
        `[nazare] Failed to destroy JS module for ${mount.key}`,
        error,
      );
    } finally {
      mounted.delete(node);
    }
  }
}

document.addEventListener("shopify:section:load", (event) => {
  initNazare(event.target);
});

document.addEventListener("shopify:section:unload", (event) => {
  destroyNazare(event.target);
});

initNazare();
