import { execFile } from "node:child_process";
import { mkdtemp, readFile, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { promisify } from "node:util";
import { afterAll, beforeAll, describe, expect, it } from "vitest";

const execFileAsync = promisify(execFile);
const cliPath = new URL("../../packages/nazare/bin/nazare.js", import.meta.url);
const packageManager = process.env.NAZARE_TEST_PACKAGE_MANAGER ?? "pnpm";

async function timedStep(name, callback) {
	const started = performance.now();
	console.info(`[theme-build] ${name} start`);
	try {
		const result = await callback();
		console.info(
			`[theme-build] ${name} done ${Math.round(performance.now() - started)}ms`,
		);
		return result;
	} catch (error) {
		console.info(
			`[theme-build] ${name} failed ${Math.round(performance.now() - started)}ms`,
		);
		throw error;
	}
}

async function runCommand(command, args, options = {}) {
	try {
		const { stdout, stderr } = await execFileAsync(command, args, {
			cwd: options.cwd,
			encoding: "utf8",
			env: { ...process.env, ...options.env },
			timeout: options.timeout,
		});
		return { code: 0, stdout, stderr };
	} catch (error) {
		return {
			code: error.code,
			stdout: error.stdout ?? "",
			stderr: error.stderr ?? "",
		};
	}
}

function runCli(args, options = {}) {
	return runCommand(process.execPath, [cliPath.pathname, ...args], options);
}

describe.sequential("nazare theme build e2e", () => {
	let cwd;
	let build;

	beforeAll(async () => {
		cwd = await mkdtemp(join(tmpdir(), "nazare-theme-build-test-"));
		console.info(`[theme-build] cwd ${cwd}`);
	});

	afterAll(async () => {
		if (cwd) {
			await rm(cwd, {
				recursive: true,
				force: true,
				maxRetries: 3,
				retryDelay: 250,
			});
		}
	});

	it("initializes a project", async () => {
		await expect(
			timedStep("init", () => runCli(["init"], { cwd, timeout: 10_000 })),
		).resolves.toMatchObject({ code: 0, stderr: "" });
	}, 15_000);

	it("pulls the default theme scaffold", async () => {
		await expect(
			timedStep("theme pull", () =>
				runCli(["theme", "pull", "--yes"], { cwd, timeout: 20_000 }),
			),
		).resolves.toMatchObject({ code: 0, stderr: "" });
	}, 25_000);

	it("installs scaffold dependencies", async () => {
		const install = await timedStep(`${packageManager} install`, () =>
			runCommand(packageManager, ["install", "--silent"], {
				cwd,
				timeout: 180_000,
			}),
		);

		expect(install).toMatchObject({ code: 0, stderr: "" });
	}, 190_000);

	it("builds the pulled theme", async () => {
		build = await timedStep(`${packageManager} run build`, () =>
			runCommand(packageManager, ["run", "build"], {
				cwd,
				timeout: 180_000,
			}),
		);

		expect(build).toMatchObject({ code: 0 });
		expect(build.stdout).toContain("vite build");
	}, 190_000);

	it("writes expected build outputs", async () => {
		await timedStep("assert outputs", async () => {
			expect(await readFile(join(cwd, "assets", "base.css"), "utf8")).toContain(
				"@layer",
			);
			expect(
				await readFile(join(cwd, "scripts", "theme.js"), "utf8"),
			).toContain("Generated by Nazare");
			expect(await readFile(join(cwd, "assets", "theme.js"), "utf8")).toContain(
				"[nazare]",
			);
		});
	}, 10_000);
});
