import { execFile } from "node:child_process";
import { mkdtemp, readFile, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { promisify } from "node:util";
import { afterEach, describe, expect, it } from "vitest";

const execFileAsync = promisify(execFile);
const cliPath = new URL("../../bin/nazare.js", import.meta.url);
const tempRoots = [];
const runSlowBuildTests = process.env.NAZARE_RUN_SLOW_TESTS === "1";

async function makeTempDir(prefix = "nazare-theme-build-test-") {
	const root = await mkdtemp(join(tmpdir(), prefix));
	tempRoots.push(root);
	return root;
}

async function runCli(args, options = {}) {
	try {
		const { stdout, stderr } = await execFileAsync(
			process.execPath,
			[cliPath.pathname, ...args],
			{
				cwd: options.cwd,
				encoding: "utf8",
				env: { ...process.env, ...options.env },
			},
		);
		return { code: 0, stdout, stderr };
	} catch (error) {
		return {
			code: error.code,
			stdout: error.stdout ?? "",
			stderr: error.stderr ?? "",
		};
	}
}

afterEach(async () => {
	await Promise.all(
		tempRoots
			.splice(0)
			.map((root) => rm(root, { recursive: true, force: true })),
	);
});

describe("nazare theme build integration", () => {
	it.skipIf(!runSlowBuildTests)(
		"pulls scaffold that can install dependencies and build",
		async () => {
			const cwd = await makeTempDir();
			await expect(runCli(["init"], { cwd })).resolves.toMatchObject({
				code: 0,
				stderr: "",
			});
			await expect(
				runCli(["theme", "pull", "--yes"], { cwd }),
			).resolves.toMatchObject({ code: 0, stderr: "" });

			const install = await execFileAsync("npm", ["install", "--silent"], {
				cwd,
				encoding: "utf8",
			});
			expect(install.stderr).toBe("");
			const build = await execFileAsync("npm", ["run", "build"], {
				cwd,
				encoding: "utf8",
			});

			expect(build.stdout).toContain("vite build");
			expect(await readFile(join(cwd, "assets", "base.css"), "utf8")).toContain(
				"@layer",
			);
			expect(
				await readFile(join(cwd, "scripts", "theme.js"), "utf8"),
			).toContain("Generated by Nazare");
			expect(await readFile(join(cwd, "assets", "theme.js"), "utf8")).toContain(
				"[nazare]",
			);
		},
		120_000,
	);
});
