import { execFile } from "node:child_process";
import { appendFile, mkdtemp, readdir, readFile, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { promisify } from "node:util";
import { afterAll, beforeAll, describe, expect, it } from "vitest";

const execFileAsync = promisify(execFile);
const cliPath = new URL(
	"../../../packages/nazare/bin/nazare.js",
	import.meta.url,
);
const registryRoot = new URL("../../../", import.meta.url).pathname;
const packageManager = process.env.NAZARE_TEST_PACKAGE_MANAGER ?? "pnpm";

async function timedStep(name, callback) {
	const started = performance.now();
	console.info(`[c-video-build] ${name} start`);
	try {
		const result = await callback();
		console.info(
			`[c-video-build] ${name} done ${Math.round(performance.now() - started)}ms`,
		);
		return result;
	} catch (error) {
		console.info(
			`[c-video-build] ${name} failed ${Math.round(performance.now() - started)}ms`,
		);
		throw error;
	}
}

async function runCommand(command, args, options = {}) {
	try {
		const { stdout, stderr } = await execFileAsync(command, args, {
			cwd: options.cwd,
			encoding: "utf8",
			env: { ...process.env, ...options.env },
			timeout: options.timeout,
		});
		return { code: 0, stdout, stderr };
	} catch (error) {
		return {
			code: error.code,
			stdout: error.stdout ?? "",
			stderr: error.stderr ?? "",
		};
	}
}

function runCli(args, options = {}) {
	return runCommand(process.execPath, [cliPath.pathname, ...args], options);
}

async function readFilesUnder(root) {
	const entries = await readdir(root, { withFileTypes: true });
	const files = [];

	for (const entry of entries) {
		const path = join(root, entry.name);
		if (entry.isDirectory()) {
			files.push(...(await readFilesUnder(path)));
		} else {
			files.push(path);
		}
	}

	return files;
}

describe.sequential("c-video production build", () => {
	let cwd;
	let build;

	beforeAll(async () => {
		cwd = await mkdtemp(join(tmpdir(), "nazare-c-video-build-test-"));
		console.info(`[c-video-build] cwd ${cwd}`);
	});

	afterAll(async () => {
		if (cwd) {
			await rm(cwd, {
				recursive: true,
				force: true,
				maxRetries: 3,
				retryDelay: 250,
			});
		}
	});

	it("creates a theme project", async () => {
		await expect(
			timedStep("init", () => runCli(["init"], { cwd, timeout: 10_000 })),
		).resolves.toMatchObject({ code: 0, stderr: "" });
	}, 15_000);

	it("pulls theme files and installs c-video", async () => {
		await expect(
			timedStep("theme pull", () =>
				runCli(["theme", "pull", "--yes"], { cwd, timeout: 20_000 }),
			),
		).resolves.toMatchObject({ code: 0, stderr: "" });

		await expect(
			timedStep("add c-video", () =>
				runCli(["add", "c-video"], {
					cwd,
					env: { NAZARE_REGISTRY_DIR: registryRoot },
					timeout: 10_000,
				}),
			),
		).resolves.toMatchObject({ code: 0, stderr: "" });
	}, 35_000);

	it("wires c-video into a rendered section", async () => {
		await timedStep("render c-video", () =>
			appendFile(
				join(cwd, "sections", "s-main.liquid"),
				"\n{% render 'c-video', video: section.settings.video %}\n",
			),
		);

		const snippet = await readFile(
			join(cwd, "snippets", "c-video.liquid"),
			"utf8",
		);
		const script = await readFile(
			join(cwd, "scripts", "snippets", "c-video.js"),
			"utf8",
		);

		expect(snippet).toContain('data-nazare-use="snippets/c-video"');
		expect(script).toContain("window.NazareVideoStore");
	}, 10_000);

	it("installs build dependencies", async () => {
		const install = await timedStep(`${packageManager} install`, () =>
			runCommand(packageManager, ["install", "--silent"], {
				cwd,
				timeout: 180_000,
			}),
		);

		expect(install).toMatchObject({ code: 0, stderr: "" });
	}, 190_000);

	it("builds c-video into production assets", async () => {
		build = await timedStep(`${packageManager} run build`, () =>
			runCommand(packageManager, ["run", "build"], {
				cwd,
				timeout: 180_000,
			}),
		);

		expect(build).toMatchObject({ code: 0 });
		expect(build.stdout).toContain("vite build");
	}, 190_000);

	it("emits runtime and c-video code", async () => {
		await timedStep("assert outputs", async () => {
			const generatedRuntime = await readFile(
				join(cwd, "scripts", "theme.js"),
				"utf8",
			);
			const assetFiles = await readFilesUnder(join(cwd, "assets"));
			const assetContents = await Promise.all(
				assetFiles.map((file) => readFile(file, "utf8")),
			);
			const bundledSource = assetContents.join("\n");

			expect(generatedRuntime).toContain("Generated by Nazare");
			expect(generatedRuntime).toContain("importModule(key)");
			expect(generatedRuntime).toContain("initNazare");
			expect(bundledSource).toContain("NazareVideoStore");
			expect(bundledSource).toContain("muteOthers");
		});
	}, 15_000);
});
